# Introduction to Linear Algebra - Week 1 Assignment

## Part II: Python Solutions

### 1. Operations on Vectors

#### Given vectors $ \mathbf{v} = [2, 4, 6, 8, 10] $ and $\mathbf{u} = [1, 3, 5, 7, 9] $.

- Component-wise Division $ \dfrac{\mathbf{v}}{\mathbf{u}} $

This requires dividing each component of $ \mathbf{v} $ by the corresponding component of $\mathbf{u} $.


In [1]:
import numpy as np
v = np.array([2, 4, 6, 8, 10])
u = np.array([1, 3, 5, 7, 9])
v_div_u = v / u
print(v_div_u)

[2.         1.33333333 1.2        1.14285714 1.11111111]


- Vector Operations $ 3\mathbf{v} - 2\mathbf{u} + \frac{1}{2}\mathbf{v} $

We calculate the operation using scalar multiplication and addition:

In [2]:
oper = 3*v - 2*u + 0.5*v
print(oper)

[ 5.  8. 11. 14. 17.]


####  b. Euclidean Norm of a Vector

Given $ \mathbf{v} = [8, 0, 5, 2, 1] $, the Euclidean norm $ \|\mathbf{v}\| $ is calculated as follows:

In [3]:
v = np.array([8, 0, 5, 2, 1])
norm_v = np.linalg.norm(v)
print(norm_v)

9.695359714832659


### 2. Determinant of a Matrix

Given the matrix $ A = \begin{pmatrix} 2 & 3 & 7 \\ -4 & 0 & 6 \\ 1 & 5 & 0 \end{pmatrix} $

We need to calculate the determinant of $ A $.

In [4]:
A = np.array([[2, 3, 7], [-4, 0, 6], [1, 5, 0]])
det_A = np.linalg.det(A)
print(det_A)

-181.99999999999997


### 3. Eigenvalue and Eigenvector Calculation for Matrix 

#### 3a. Matrix $B$
Given the matrix:
$$ B = \begin{pmatrix} 3 & 2 & 4 \\ 2 & 0 & 2 \\ 4 & 2 & 3 \end{pmatrix} $$

- Finding Eigenvalues and Eigenvectors

In [5]:
B = np.array([[3, 2, 4], [2, 0, 2], [4, 2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(B)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-1.  8. -1.]
Eigenvectors:
 [[-0.74535599  0.66666667 -0.21539222]
 [ 0.2981424   0.33333333 -0.77010996]
 [ 0.59628479  0.66666667  0.6004472 ]]


#### 3b. Matrix $D$

#### Given Matrix and Vectors:

- Matrix $D $:
  
  $$
  D = \begin{pmatrix}
  3 & 1 & 2 \\
  1 & 3 & 1 \\
  2 & 1 & 3
  \end{pmatrix}
  $$

- Vector $ \mathbf{v}_1 = [1, 1, 1] $

- Vector $\mathbf{v}_2 = [-1, 1, -1] $

#### Task:
Check if $ \mathbf{v}_1 $ and $ \mathbf{v}_2 $ are eigenvectors of matrix $ D $ and print the results along with any corresponding eigenvalues.

In [12]:
D = np.array([[3, 1, 2], [1, 3, 1], [2, 1, 3]])
v1 = np.array([1, 1, 1])
v2 = np.array([-1, 1, -1])
Dv1 = D.dot(v1)
Dv2 = D.dot(v2)
print("D * v1:", Dv1)
print("D * v2:", Dv2)

D * v1: [6 5 6]
D * v2: [-4  1 -4]


Neither $ \mathbf{v}_1 $ nor $\mathbf{v}_2 $ are eigenvectors of the matrix $ D $ because there is not value of $\lambda$ that can satisfy the values of $D\cdot \mathbf{v_1}= \lambda\cdot \mathbf{v_1}$ and $D\cdot \mathbf{v_2} = \lambda\cdot \mathbf{v_2}$.

In [13]:
def is_eigenvector(matrix, vector):
    result = np.dot(matrix, vector)
    
    lambda_candidates = result / vector
    
    if np.allclose(lambda_candidates, lambda_candidates[0]):
        return True, lambda_candidates[0]  # It is an eigenvector, return True and the eigenvalue
    else:
        return False, None  # It is not an eigenvector

# Check for v1
is_v1_eigen, lambda_v1 = is_eigenvector(D, v1)
print("v1 is an eigenvector of D:", is_v1_eigen, "with eigenvalue:", lambda_v1)

# Check for v2
is_v2_eigen, lambda_v2 = is_eigenvector(D, v2)
print("v2 is an eigenvector of D:", is_v2_eigen, "with eigenvalue:", lambda_v2)

v1 is an eigenvector of D: False with eigenvalue: None
v2 is an eigenvector of D: False with eigenvalue: None


### 4. PCA and Variance Calculation

Steps to perform PCA on given dataset $ X = \{ (4, 2, 3), (3, 13, 4), (9, 4, 5), (0, 5, 7) \} $:

#### Step 1: Standardization

Calculate mean and standard deviation for each feature, and standardize the dataset.

In [6]:
X = np.array([[4, 2, 3], [3, 13, 4], [9, 4, 5], [0, 5, 7]])
means = np.mean(X, axis=0)
stds = np.std(X, axis=0)
Z = (X - means) / stds

#### Step 2: Compute Covariance Matrix

In [7]:
cov_matrix = np.cov(Z, rowvar=False)

#### Step 3: Eigenvalue and Eigenvector Computation

In [8]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

#### Step 4 and 5: Feature Vector and Data Recasting

Select largest eigenvalues and corresponding eigenvectors, then transform the dataset.

In [9]:
# Select top 2 eigenvectors
feature_vector = eigenvectors[:, :2]
pca_result = np.dot(Z, feature_vector)
print(pca_result)

[[ 1.09646687 -1.04315003]
 [-0.1830494   0.51600533]
 [-0.96806447 -1.18256916]
 [ 0.054647    1.70971385]]


#### Variance Explained

Calculate the percentage of variance explained by each principal component.

In [10]:
total_variance = sum(eigenvalues)
variance_explained = [(i / total_variance) * 100 for i in eigenvalues]
print(variance_explained)


[18.13234827367028, 47.30012301758761, 34.56752870874211]


### Question 4 (sklearn PCA)

In [11]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
variance_explained = pca.explained_variance_ratio_
print("PCA transformed data:\n", X_pca)
print("Variance explained by each component:", variance_explained) # This gives the variance for only the top 2 eigenvectors

PCA transformed data:
 [[-3.75915536  1.06811586]
 [ 6.85288785 -1.82352429]
 [-3.69939144 -3.72913197]
 [ 0.60565895  4.48454039]]
Variance explained by each component: [0.62232415 0.31870509]
